server:
  port: 8080
  forward-headers-strategy: framework
spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/momentree_prod?serverTimezone=Asia/Seoul&cacheDefaultTimezone=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: tree1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'
    time-zone: UTC
custom:
  site:
    name: "MOMENTREE"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"