server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/momentree_prod
    username: root
    password: tree1234
    driver-class-name: com.mysql.cj.jdbc.Driver
custom:
  site:
    name: "MOMENTREE"
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"