server:
  port: 8080
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true